/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author valmi
 */
public class Frm_MenuAdmin extends javax.swing.JFrame {

    /**
     * Creates new form Frm_Menu
     */
    public Frm_MenuAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jmb_opcionAdmin = new javax.swing.JMenu();
        jm_producto = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jmi_listarProd = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jm_garzones = new javax.swing.JMenu();
        jmi_agregarGarzon = new javax.swing.JMenuItem();
        jmi_editarGarzon = new javax.swing.JMenuItem();
        jmi_listarGarzon = new javax.swing.JMenuItem();
        jmi_borrarGarzon = new javax.swing.JMenuItem();
        jm_mesas = new javax.swing.JMenu();
        jmi_agregarMesa = new javax.swing.JMenuItem();
        jmi_listarMesa = new javax.swing.JMenuItem();
        jmi_borrarMesa = new javax.swing.JMenuItem();
        jmb_cerrarSesionAdmin = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/M-system-logo.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setToolTipText("");

        jmb_opcionAdmin.setText("Opciones");

        jm_producto.setText("Productos");

        jMenuItem9.setText("Agregar");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jm_producto.add(jMenuItem9);

        jMenuItem10.setText("Editar");
        jm_producto.add(jMenuItem10);

        jmi_listarProd.setText("Listar");
        jm_producto.add(jmi_listarProd);

        jMenuItem12.setText("Borrar");
        jm_producto.add(jMenuItem12);

        jmb_opcionAdmin.add(jm_producto);

        jm_garzones.setText("Garzones");

        jmi_agregarGarzon.setText("Agregar");
        jmi_agregarGarzon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_agregarGarzonActionPerformed(evt);
            }
        });
        jm_garzones.add(jmi_agregarGarzon);

        jmi_editarGarzon.setText("Editar");
        jm_garzones.add(jmi_editarGarzon);

        jmi_listarGarzon.setText("Listar");
        jm_garzones.add(jmi_listarGarzon);

        jmi_borrarGarzon.setText("Borrar");
        jm_garzones.add(jmi_borrarGarzon);

        jmb_opcionAdmin.add(jm_garzones);

        jm_mesas.setText("Mesas");

        jmi_agregarMesa.setText("Agregar");
        jm_mesas.add(jmi_agregarMesa);

        jmi_listarMesa.setText("Listar");
        jm_mesas.add(jmi_listarMesa);

        jmi_borrarMesa.setText("Borrar");
        jm_mesas.add(jmi_borrarMesa);

        jmb_opcionAdmin.add(jm_mesas);

        jMenuBar2.add(jmb_opcionAdmin);

        jmb_cerrarSesionAdmin.setText("Cerrar Sesion");
        jMenuBar2.add(jmb_cerrarSesionAdmin);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(89, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        //
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jmi_agregarGarzonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_agregarGarzonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmi_agregarGarzonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_MenuAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenu jm_garzones;
    private javax.swing.JMenu jm_mesas;
    private javax.swing.JMenu jm_producto;
    private javax.swing.JMenu jmb_cerrarSesionAdmin;
    private javax.swing.JMenu jmb_opcionAdmin;
    private javax.swing.JMenuItem jmi_agregarGarzon;
    private javax.swing.JMenuItem jmi_agregarMesa;
    private javax.swing.JMenuItem jmi_borrarGarzon;
    private javax.swing.JMenuItem jmi_borrarMesa;
    private javax.swing.JMenuItem jmi_editarGarzon;
    private javax.swing.JMenuItem jmi_listarGarzon;
    private javax.swing.JMenuItem jmi_listarMesa;
    private javax.swing.JMenuItem jmi_listarProd;
    // End of variables declaration//GEN-END:variables
}
