package Vista;

import Controlador.RegistroMesa;
import Modelo.Mesa;
import javax.swing.JOptionPane;

/**
 * @author opazo-oses-pincheira-sanchez nov 2024
 */
public class Frm_MenuAdmin extends javax.swing.JFrame {

    /**
     * Creates new form Frm_Menu
     */
    public Frm_MenuAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jbtn_cerrarSesion = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        jmb_opcionAdmin = new javax.swing.JMenu();
        jm_producto = new javax.swing.JMenu();
        jmi_agregarProd = new javax.swing.JMenuItem();
        jmi_editarProd = new javax.swing.JMenuItem();
        jmi_listarProd = new javax.swing.JMenuItem();
        jmi_borrarProd = new javax.swing.JMenuItem();
        jm_garzones = new javax.swing.JMenu();
        jmi_agregarGarzon = new javax.swing.JMenuItem();
        jmi_editarGarzon = new javax.swing.JMenuItem();
        jmi_listarGarzon = new javax.swing.JMenuItem();
        jmi_borrarGarzon = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Candara Light", 1, 24)); // NOI18N
        jLabel1.setText("MENU ADMINISTRADOR");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/cocinero (1).png"))); // NOI18N

        jbtn_cerrarSesion.setFont(new java.awt.Font("Candara Light", 1, 14)); // NOI18N
        jbtn_cerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/cerrar-sesion.png"))); // NOI18N
        jbtn_cerrarSesion.setText("Cerrar Sesion");
        jbtn_cerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_cerrarSesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(jLabel1)
                .addGap(0, 121, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtn_cerrarSesion)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbtn_cerrarSesion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jmb_opcionAdmin.setText("Opciones");

        jm_producto.setText("Productos");
        jm_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_productoActionPerformed(evt);
            }
        });

        jmi_agregarProd.setText("Agregar");
        jmi_agregarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_agregarProdActionPerformed(evt);
            }
        });
        jm_producto.add(jmi_agregarProd);

        jmi_editarProd.setText("Editar");
        jmi_editarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_editarProdActionPerformed(evt);
            }
        });
        jm_producto.add(jmi_editarProd);

        jmi_listarProd.setText("Listar");
        jmi_listarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_listarProdActionPerformed(evt);
            }
        });
        jm_producto.add(jmi_listarProd);

        jmi_borrarProd.setText("Borrar");
        jmi_borrarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_borrarProdActionPerformed(evt);
            }
        });
        jm_producto.add(jmi_borrarProd);

        jmb_opcionAdmin.add(jm_producto);

        jm_garzones.setText("Garzones");

        jmi_agregarGarzon.setText("Agregar");
        jmi_agregarGarzon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_agregarGarzonActionPerformed(evt);
            }
        });
        jm_garzones.add(jmi_agregarGarzon);

        jmi_editarGarzon.setText("Editar");
        jmi_editarGarzon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_editarGarzonActionPerformed(evt);
            }
        });
        jm_garzones.add(jmi_editarGarzon);

        jmi_listarGarzon.setText("Listar");
        jmi_listarGarzon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_listarGarzonActionPerformed(evt);
            }
        });
        jm_garzones.add(jmi_listarGarzon);

        jmi_borrarGarzon.setText("Borrar");
        jmi_borrarGarzon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_borrarGarzonActionPerformed(evt);
            }
        });
        jm_garzones.add(jmi_borrarGarzon);

        jmb_opcionAdmin.add(jm_garzones);

        jMenuBar2.add(jmb_opcionAdmin);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmi_agregarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_agregarProdActionPerformed
        Frm_AgregarProducto agregarProducto = new Frm_AgregarProducto();
        agregarProducto.setVisible(true); 
        agregarProducto.setLocationRelativeTo(null); //Centra la ventana en la pantalla
    }//GEN-LAST:event_jmi_agregarProdActionPerformed

    private void jmi_agregarGarzonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_agregarGarzonActionPerformed
        Frm_agregarGarzon agregarGarzon = new Frm_agregarGarzon();
        agregarGarzon.setVisible(true);
        agregarGarzon.setLocationRelativeTo(null); // Centra la ventana en la pantalla
    }//GEN-LAST:event_jmi_agregarGarzonActionPerformed

    private void jmi_editarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_editarProdActionPerformed
        Frm_EditarProd editarProducto = new Frm_EditarProd();
        editarProducto.setVisible(true);
        editarProducto.setLocationRelativeTo(null);//Centra la ventana en la pantalla
    }//GEN-LAST:event_jmi_editarProdActionPerformed

    private void jmi_listarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_listarProdActionPerformed
        Frm_ListarProd listarProducto = new Frm_ListarProd();
        listarProducto.setVisible(true);
        listarProducto.setLocationRelativeTo(null);//Centra la ventana en la pantalla
    }//GEN-LAST:event_jmi_listarProdActionPerformed

    private void jmi_borrarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_borrarProdActionPerformed
        Frm_EliminarProd borrarProducto = new Frm_EliminarProd();
        borrarProducto.setVisible(true);
        borrarProducto.setLocationRelativeTo(null);//Centra la ventana en la pantalla
    }//GEN-LAST:event_jmi_borrarProdActionPerformed

    private void jmi_editarGarzonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_editarGarzonActionPerformed
        Frm_editarGarzon editarGarzon = new Frm_editarGarzon();
        editarGarzon.setVisible(true);
        editarGarzon.setLocationRelativeTo(null); // Centra la ventana en la pantalla
    }//GEN-LAST:event_jmi_editarGarzonActionPerformed

    private void jmi_listarGarzonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_listarGarzonActionPerformed
        Frm_listarGarzon listarGarzon = new Frm_listarGarzon();
        listarGarzon.setVisible(true);
        listarGarzon.setLocationRelativeTo(null);// Centra la ventana en la pantalla
    }//GEN-LAST:event_jmi_listarGarzonActionPerformed

    private void jmi_borrarGarzonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_borrarGarzonActionPerformed
        Frm_eliminarGarzon eliminarGarzon = new Frm_eliminarGarzon();
        eliminarGarzon.setVisible(true);
        eliminarGarzon.setLocationRelativeTo(null);// Centra la ventana en la pantalla
    }//GEN-LAST:event_jmi_borrarGarzonActionPerformed

    private void jbtn_cerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_cerrarSesionActionPerformed
        Frm_InicioSesion is = new Frm_InicioSesion();
        is.setVisible(true);
        dispose();
    }//GEN-LAST:event_jbtn_cerrarSesionActionPerformed

    private void jm_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_productoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jm_productoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_MenuAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtn_cerrarSesion;
    private javax.swing.JMenu jm_garzones;
    private javax.swing.JMenu jm_producto;
    private javax.swing.JMenu jmb_opcionAdmin;
    private javax.swing.JMenuItem jmi_agregarGarzon;
    private javax.swing.JMenuItem jmi_agregarProd;
    private javax.swing.JMenuItem jmi_borrarGarzon;
    private javax.swing.JMenuItem jmi_borrarProd;
    private javax.swing.JMenuItem jmi_editarGarzon;
    private javax.swing.JMenuItem jmi_editarProd;
    private javax.swing.JMenuItem jmi_listarGarzon;
    private javax.swing.JMenuItem jmi_listarProd;
    // End of variables declaration//GEN-END:variables
}
