package Vista;

import Controlador.RegistroTrabajador;
import Modelo.Trabajador;
import javax.swing.JOptionPane;

/**
 * @author opazo-oses-pincheira-sanchez nov 2024
 */
public class Frm_editarGarzon extends javax.swing.JFrame {

    /**
     * Creates new form Frm_editarGarzon
     */
    public Frm_editarGarzon() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtxt_idGarzon = new javax.swing.JTextField();
        Jbtn_volverGarzon = new javax.swing.JButton();
        jbtn_editarGarzon = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Candara Light", 1, 24)); // NOI18N
        jLabel1.setText("Actualizar Garzon");
        jLabel1.setPreferredSize(new java.awt.Dimension(133, 19));

        jLabel2.setFont(new java.awt.Font("Candara Light", 1, 14)); // NOI18N
        jLabel2.setText("ID Garzon:");
        jLabel2.setMaximumSize(new java.awt.Dimension(67, 16));
        jLabel2.setMinimumSize(new java.awt.Dimension(67, 16));
        jLabel2.setPreferredSize(new java.awt.Dimension(67, 16));

        jtxt_idGarzon.setFont(new java.awt.Font("Candara Light", 1, 14)); // NOI18N
        jtxt_idGarzon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_idGarzonActionPerformed(evt);
            }
        });

        Jbtn_volverGarzon.setFont(new java.awt.Font("Candara Light", 1, 14)); // NOI18N
        Jbtn_volverGarzon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/devolver.png"))); // NOI18N
        Jbtn_volverGarzon.setText("Volver");
        Jbtn_volverGarzon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn_volverGarzonActionPerformed(evt);
            }
        });

        jbtn_editarGarzon.setFont(new java.awt.Font("Candara Light", 1, 14)); // NOI18N
        jbtn_editarGarzon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/editar.png"))); // NOI18N
        jbtn_editarGarzon.setText("Editar");
        jbtn_editarGarzon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_editarGarzonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jbtn_editarGarzon)
                            .addGap(74, 74, 74)
                            .addComponent(Jbtn_volverGarzon))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jtxt_idGarzon, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxt_idGarzon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jbtn_volverGarzon)
                    .addComponent(jbtn_editarGarzon))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxt_idGarzonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_idGarzonActionPerformed
        // TODO add your handling code here:
        String input = jtxt_idGarzon.getText().trim();

        // Si el campo está vacío, mostrar mensaje y salir
        if (input.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese una ID de garzón.");
            return;
        }

        // Verificar si lo ingresado es una ID válida (suponiendo que es un UUID)
        if (input.length() == 36) { // Verificar si la longitud es la de un UUID
            RegistroTrabajador registro = new RegistroTrabajador();
            Trabajador trabajador = registro.buscarPorId(input); // Buscar al trabajador por la ID ingresada

            if (trabajador == null) {
                JOptionPane.showMessageDialog(this, "Garzón no encontrado con la ID proporcionada.");
                return;
            }

            // Si se encuentra al trabajador, mostrar el nombre actual en el campo correspondiente
            // Suponiendo que Jtxt_nombreGarzon es el campo donde se edita el nombre
            jtxt_idGarzon.setText(trabajador.getNom_trab());  // Mostrar el nombre del trabajador en Jtxt_idGarzon (este campo también puede ser para mostrar el nombre)
        } else {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese una ID de garzón válida.");
        }
    }//GEN-LAST:event_jtxt_idGarzonActionPerformed

    private void Jbtn_volverGarzonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn_volverGarzonActionPerformed
        dispose();
    }//GEN-LAST:event_Jbtn_volverGarzonActionPerformed

    private void jbtn_editarGarzonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_editarGarzonActionPerformed
        
        String id_garzon = this.jtxt_idGarzon.getText().trim();

        if (id_garzon.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor, ingrese un ID válido", "Validación", JOptionPane.WARNING_MESSAGE);
            this.jtxt_idGarzon.requestFocus();
            return;
        }

        RegistroTrabajador rt = new RegistroTrabajador();

        Trabajador trabajador = rt.buscarPorId(id_garzon); // Implementa este método para obtener un producto de la BD

        if (trabajador == null) {
            JOptionPane.showMessageDialog(null, "Garzón no encontrado con el ID ingresado", "Error", JOptionPane.ERROR_MESSAGE);
            this.jtxt_idGarzon.requestFocus();
            return;
        }

        // Edición de los datos 
        String nuevoNombre = JOptionPane.showInputDialog(null, "Editar nombre del garzón:", trabajador.getNom_trab());
        if (nuevoNombre != null && !nuevoNombre.trim().isEmpty()) {
            trabajador.setNom_trab(nuevoNombre.trim());
        }

        

        // Método actualizarProducto para guardar los cambios
        boolean actualizado = rt.actualizarTrabajador(trabajador);

        if (actualizado) {
            JOptionPane.showMessageDialog(null, "Garzón actualizado correctamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Error al actualizar garzón en la base de datos", "Error", JOptionPane.ERROR_MESSAGE);
        }




// Obtener el valor de la ID ingresada en el campo Jtxt_idGarzon
//        String idGarzon = Jtxt_idGarzon.getText().trim();
//
//        // Verificar si el campo de ID está vacío
//        if (idGarzon.isEmpty()) {
//            JOptionPane.showMessageDialog(this, "Por favor, ingrese la ID del garzón.");
//            return;
//        }
//
//        // Buscar al trabajador usando la ID ingresada
//        Trabajador trabajador = new RegistroTrabajador().buscarPorId(idGarzon);
//
//        // Verificar si el trabajador fue encontrado
//        if (trabajador == null) {
//            JOptionPane.showMessageDialog(this, "No se encontró al trabajador con esa ID.");
//            return;
//        }
//        
//        // Obtener el nuevo nombre del trabajador desde el campo de texto
//        String nuevoNombre = Jtxt_idGarzon.getText().trim();
//
//        // Verificar si el nuevo nombre no está vacío
//        if (nuevoNombre.isEmpty()) {
//            JOptionPane.showMessageDialog(this, "Por favor, ingrese un nuevo nombre.");
//            return;
//        }
//
//        // Actualizar el nombre del trabajador en la base de datos
//        trabajador.setNom_trab(nuevoNombre);  // Establecer el nuevo nombre en el objeto Trabajador
//
//        // Llamar al método para actualizar el nombre del trabajador en la base de datos
//        boolean exito = new RegistroTrabajador().actualizarTrabajador(trabajador);
//
//        // Verificar si la actualización fue exitosa
//        if (exito) {
//            JOptionPane.showMessageDialog(this, "Nombre de garzón actualizado con éxito.");
//        } else {
//            JOptionPane.showMessageDialog(this, "No se pudo actualizar el nombre del garzón.");
//        }
    }//GEN-LAST:event_jbtn_editarGarzonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_editarGarzon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_editarGarzon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_editarGarzon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_editarGarzon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_editarGarzon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Jbtn_volverGarzon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbtn_editarGarzon;
    private javax.swing.JTextField jtxt_idGarzon;
    // End of variables declaration//GEN-END:variables
}
