package Vista;

import Controlador.RegistroTrabajador;
import Modelo.Trabajador;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 * @author opazo-oses-pincheira-sanchez nov 2024
 */
public class Frm_listarGarzon extends javax.swing.JFrame {

    /**
     * Creates new form Frm_listarGarzon
     */
    public Frm_listarGarzon() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Jtxt_ingresarIdGarzon = new javax.swing.JTextField();
        Jbtn_listarGarzon = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Jtb_listadoGarzon = new javax.swing.JTable();
        jbtn_volverGarzon = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Candara Light", 1, 14)); // NOI18N
        jLabel1.setText("Ingresar ID:");

        Jtxt_ingresarIdGarzon.setFont(new java.awt.Font("Candara Light", 1, 14)); // NOI18N

        Jbtn_listarGarzon.setFont(new java.awt.Font("Candara Light", 1, 14)); // NOI18N
        Jbtn_listarGarzon.setText("Listar");
        Jbtn_listarGarzon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn_listarGarzonActionPerformed(evt);
            }
        });

        Jtb_listadoGarzon.setFont(new java.awt.Font("Candara Light", 1, 14)); // NOI18N
        Jtb_listadoGarzon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID Garzon", "Nombre Garzon"
            }
        ));
        Jtb_listadoGarzon.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                Jtb_listadoGarzonAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(Jtb_listadoGarzon);

        jbtn_volverGarzon.setFont(new java.awt.Font("Candara Light", 1, 14)); // NOI18N
        jbtn_volverGarzon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/devolver.png"))); // NOI18N
        jbtn_volverGarzon.setText("Volver");
        jbtn_volverGarzon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_volverGarzonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Jtxt_ingresarIdGarzon, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(Jbtn_listarGarzon))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jbtn_volverGarzon)
                .addGap(16, 16, 16))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Jtxt_ingresarIdGarzon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jbtn_listarGarzon, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jbtn_volverGarzon)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Jbtn_listarGarzonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn_listarGarzonActionPerformed
        // TODO add your handling code here:

        String nom_trab, id_trab;

        RegistroTrabajador rg = new RegistroTrabajador();
        DefaultTableModel modelo = (DefaultTableModel) this.Jtb_listadoGarzon.getModel();

        try {
            id_trab = this.Jtxt_ingresarIdGarzon.getText().trim();
        } catch (Exception e) {
            id_trab = "";
        }

        modelo.setRowCount(0);

        if (id_trab.isEmpty()) { // Listar a todos
            List<Trabajador> lista = rg.listarTrabajador();

            for (Trabajador tmp : lista) {
                id_trab = tmp.getId_trab();
                nom_trab = tmp.getNom_trab();

                modelo.addRow(new Object[]{id_trab, nom_trab});
            }
        } else { // Listar por id
            Trabajador trabajador = rg.buscarPorId(id_trab);
            if (trabajador != null) {
                id_trab = trabajador.getId_trab();
                nom_trab = trabajador.getNom_trab();

                modelo.addRow(new Object[]{id_trab, nom_trab});
            } else {
                // Opcional: mostrar un mensaje si no se encuentra Garzon
                javax.swing.JOptionPane.showMessageDialog(this, "Garzon no encontrado.");
            }
        }

    }//GEN-LAST:event_Jbtn_listarGarzonActionPerformed

    private void Jtb_listadoGarzonAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_Jtb_listadoGarzonAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtb_listadoGarzonAncestorAdded

    private void jbtn_volverGarzonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_volverGarzonActionPerformed
        dispose();
    }//GEN-LAST:event_jbtn_volverGarzonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_listarGarzon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_listarGarzon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_listarGarzon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_listarGarzon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_listarGarzon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Jbtn_listarGarzon;
    private javax.swing.JTable Jtb_listadoGarzon;
    private javax.swing.JTextField Jtxt_ingresarIdGarzon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtn_volverGarzon;
    // End of variables declaration//GEN-END:variables
}
